name: Deploy Build Folder to Server

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: almaraacompany.com
        username: ${{ secrets.server_master_turki_name }}
        password: ${{ secrets.server_master_turki_password }}
        local-dir: ./dist/
        server-dir: /public_html/dashboard-v3/ # Target directory on the server
        protocol: ftps
        port: 21
